### ISSUE TITLE
App crashes when launched in emulator

### ISSUE THREAD

**Issue by Tyler-R** [SFU-Embedded-Cosplay/Halo-Suit-Android#2]
When the app is launched in the emulator it crashes due to mAdapter being null.  This likely has to do with this line

mAdapter = BluetoothAdapter.getDefaultAdapter();

in AndroidBlue's constructor returning null.
We should have some way of dealing with this in the emulator such as automatically switching to the socket implementation or displaying a warning message and then not allowing people to proceed.  Its very likely BluetoothAdapter not work on the emulator.

**Comment by abrykajlo** [comment]
The emulator can't emulate bluetooth. This is a well known problem with android

**Comment by abrykajlo** [comment]
http://stackoverflow.com/questions/22604305/how-to-use-android-emulator-for-testing-bluetooth-application

**Comment by Tyler-R** [comment]
We still might want to look into displaying a warning message before closing the app, rather than just crashing it.  If the app just crashes people could end up wasting time wondering why it is not working.

**Comment by Tyler-R** [comment]
We should have some way in general to handle when a phone does not support bluetooth at all if we want so if someone enters the project and loads the program onto their phone and they don't have bluetooth support they are notified in a user friendly way
