### ISSUE TITLE
settings buttons do not give feedback

### ISSUE THREAD

**Issue by Tyler-R** [SFU-Embedded-Cosplay/Halo-Suit-Android#5]
The three buttons inside of the settings fragment: "Start Discovery", "Lock Configuration", and "Reset Configuration" don't give any feed when clicked aside from a clicking sound.  It would be nice if they lit up or gave some kind of visual feedback that indicated that they worked and that something happens when they are clicked.

It would also be nice if "Start Discovery" gave some kind of advanced feedback that indicated that the system is currently looking for another Bluetooth devices to pair with it.  I was thinking something like a spinner wheel that displays while your looking for other devices.  It may also be a good idea to only look for other Bluetooth devices for 10 or 20 seconds before stopping.  This could be synced up with the spinner or other form of display.

**Comment by landalex** [comment]
Fixed by 583e5cfa3c4c1ae28b4c21ec9695a3b19753f8bf
